<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Film;
use Carbon\Carbon;

class FilmSeeder extends Seeder
{
    public function run()
    {
        Film::truncate();
        $now = Carbon::now();

        $film = [
            // ─── CATEGORIA 1: Horror ────────────────────────────────────────
            [
                'idCategoria' => 1,
                'titolo'      => 'The Shining',
                'descrizione' => 'Uno scrittore accetta di fare il guardiano invernale di un hotel isolato portando con sé la famiglia; l\'hotel è infestato da una presenza maligna che lo indebolisce.',
                'durata'      => 146,
                'regista'     => 'Stanley Kubrick',
                'attori'      => 'Jack Nicholson, Shelley Duvall',
                'anno'        => 1980,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/Shining.jpg',
                'carousel'    => 'assets/img/horror.jpg',
                'video'       => 'assets/video/shining.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 1,
                'titolo'      => 'IT',
                'descrizione' => 'Un gruppo di bambini sfida un\'entità malvagia che periodicamente emerge dalle fognature di Derry per divorare i bambini della città.',
                'durata'      => 135,
                'regista'     => 'Andy Muschietti',
                'attori'      => 'Bill Skarsgård, Jaeden Martell',
                'anno'        => 2017,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/IT.jpg',
                'carousel'    => 'assets/img/horror.jpg',
                'video'       => 'assets/video/IT.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 1,
                'titolo'      => 'L\'Esorcista',
                'descrizione' => 'Una ragazza di 12 anni viene posseduta da un\'entità demoniaca; sua madre chiede l\'aiuto di due sacerdoti per esorcizzare il demone.',
                'durata'      => 122,
                'regista'     => 'William Friedkin',
                'attori'      => 'Ellen Burstyn, Linda Blair',
                'anno'        => 1973,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/horror.jpg',
                'carousel'    => 'assets/img/horror.jpg',
                'video'       => 'assets/video/IT.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 1,
                'titolo'      => 'A Quiet Place',
                'descrizione' => 'Una famiglia sopravvive in un mondo post-apocalittico abitato da creature che cacciano esclusivamente mediante il suono.',
                'durata'      => 90,
                'regista'     => 'John Krasinski',
                'attori'      => 'Emily Blunt, John Krasinski',
                'anno'        => 2018,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/a-quiet-place.jpg',
                'carousel'    => 'assets/img/horror.jpg',
                'video'       => 'assets/video/quiet-place.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 1,
                'titolo'      => 'Get Out',
                'descrizione' => 'Un giovane afroamericano visita la famiglia della fidanzata bianca e scopre che dietro la cortesia si nasconde un terribile segreto.',
                'durata'      => 104,
                'regista'     => 'Jordan Peele',
                'attori'      => 'Daniel Kaluuya, Allison Williams',
                'anno'        => 2017,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/Get-Out.jpg',
                'carousel'    => 'assets/img/horror.jpg',
                'video'       => 'assets/video/get-out.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 1,
                'titolo'      => 'Hereditary',
                'descrizione' => 'Dopo la morte della matriarca, la famiglia Graham si trova a fare i conti con segreti oscuri legati al loro albero genealogico.',
                'durata'      => 127,
                'regista'     => 'Ari Aster',
                'attori'      => 'Toni Collette, Alex Wolff',
                'anno'        => 2018,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/Hereditary.jpg',
                'carousel'    => 'assets/img/horror.jpg',
                'video'       => 'assets/video/hereditary.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 1,
                'titolo'      => 'Midsommar',
                'descrizione' => 'Una coppia in crisi si reca in Svezia per un festival estivo che si rivela essere un rituale pagano oscuro e sanguinario.',
                'durata'      => 148,
                'regista'     => 'Ari Aster',
                'attori'      => 'Florence Pugh, Jack Reynor',
                'anno'        => 2019,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/midsommar.jpg',
                'carousel'    => 'assets/img/horror.jpg',
                'video'       => 'assets/video/midsommar.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],

            // ─── CATEGORIA 2: Commedia ──────────────────────────────────────
            [
                'idCategoria' => 2,
                'titolo'      => 'La Vita è Bella',
                'descrizione' => 'Un padre ebreo-italiano usa la sua immaginazione per proteggere suo figlio dagli orrori di un campo di concentramento nazista.',
                'durata'      => 116,
                'regista'     => 'Roberto Benigni',
                'attori'      => 'Roberto Benigni, Nicoletta Braschi',
                'anno'        => 1997,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/La-vita-e-bella.jpg',
                'carousel'    => 'assets/img/commedia.jpg',
                'video'       => 'assets/video/la-vita-e-bella.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 2,
                'titolo'      => 'Benvenuti al Sud',
                'descrizione' => 'Un impiegato delle poste milanese viene trasferito in un piccolo paese della Campania e scopre un sud diverso da quello immaginato.',
                'durata'      => 102,
                'regista'     => 'Luca Miniero',
                'attori'      => 'Claudio Bisio, Alessandro Siani',
                'anno'        => 2010,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/Benvenuti-al-Sud.jpg',
                'carousel'    => 'assets/img/commedia.jpg',
                'video'       => 'assets/video/benvenuti-al-sud.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 2,
                'titolo'      => 'Perfetti Sconosciuti',
                'descrizione' => 'Durante una cena tra amici si decide di mettere in comune tutti i messaggi e le chiamate del cellulare: emergono segreti inaspettati.',
                'durata'      => 97,
                'regista'     => 'Paolo Genovese',
                'attori'      => 'Marco Giallini, Kasia Smutniak',
                'anno'        => 2016,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/perfetti-sconosciuti.jpg',
                'carousel'    => 'assets/img/commedia.jpg',
                'video'       => 'assets/video/perfetti-sconosciuti.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 2,
                'titolo'      => 'Il Cacciatore di Dote',
                'descrizione' => 'Due avvocati matrimonialisti cercano di sedurre e sposare ricche ereditiere, finché non incontrano le donne della loro vita.',
                'durata'      => 119,
                'regista'     => 'David Dobkin',
                'attori'      => 'Owen Wilson, Vince Vaughn',
                'anno'        => 2005,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/Il-cacciatore-di-dote.jpg',
                'carousel'    => 'assets/img/commedia.jpg',
                'video'       => 'assets/video/cacciatore-dote.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 2,
                'titolo'      => 'Una Notte da Leoni',
                'descrizione' => 'Tre amici si risvegliano a Las Vegas senza ricordare nulla della notte precedente e devono trovare il quarto amico per farlo arrivare al matrimonio.',
                'durata'      => 100,
                'regista'     => 'Todd Phillips',
                'attori'      => 'Bradley Cooper, Zach Galifianakis',
                'anno'        => 2009,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/una-notte-da-leoni.jpg',
                'carousel'    => 'assets/img/commedia.jpg',
                'video'       => 'assets/video/una-notte-da-leoni.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 2,
                'titolo'      => 'Superbad',
                'descrizione' => 'Due liceali sul punto di diplomarsi cercano di procurarsi alcolici per una festa e vivono una notte di avventure fuori controllo.',
                'durata'      => 113,
                'regista'     => 'Greg Mottola',
                'attori'      => 'Jonah Hill, Michael Cera',
                'anno'        => 2007,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/super-bad.jpg',
                'carousel'    => 'assets/img/commedia.jpg',
                'video'       => 'assets/video/superbad.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 2,
                'titolo'      => 'Bianco, Rosso e Verdone',
                'descrizione' => 'Tre italiani tormentati affrontano un viaggio in auto da Roma verso i seggi elettorali nelle rispettive città di origine.',
                'durata'      => 110,
                'regista'     => 'Carlo Verdone',
                'attori'      => 'Carlo Verdone, Suso Cecchi D\'Amico',
                'anno'        => 1981,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/Bianco-rosso-verdone.jpg',
                'carousel'    => 'assets/img/commedia.jpg',
                'video'       => 'assets/video/verdone.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],

            // ─── CATEGORIA 3: Azione ────────────────────────────────────────
            [
                'idCategoria' => 3,
                'titolo'      => 'Inception',
                'descrizione' => 'Un ladro esperto nell\'arte di entrare nei sogni altrui viene ingaggiato per compiere l\'impossibile: inserire un\'idea nella mente di qualcuno.',
                'durata'      => 148,
                'regista'     => 'Christopher Nolan',
                'attori'      => 'Leonardo DiCaprio, Marion Cotillard',
                'anno'        => 2010,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/inception.jpg',
                'carousel'    => 'assets/img/elenco.jpg',
                'video'       => 'assets/video/inception.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 3,
                'titolo'      => 'Mad Max: Fury Road',
                'descrizione' => 'In un futuro post-apocalittico, Max si allea con Furiosa per sfuggire a un tiranno e attraversare il deserto verso la libertà.',
                'durata'      => 120,
                'regista'     => 'George Miller',
                'attori'      => 'Tom Hardy, Charlize Theron',
                'anno'        => 2015,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/mad-max.jpg',
                'carousel'    => 'assets/img/elenco.jpg',
                'video'       => 'assets/video/mad-max.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 3,
                'titolo'      => 'John Wick',
                'descrizione' => 'Un ex sicario ritorna in azione dopo che una banda di criminali gli uccide il cane, ultimo ricordo della moglie scomparsa.',
                'durata'      => 101,
                'regista'     => 'Chad Stahelski',
                'attori'      => 'Keanu Reeves, Michael Nyqvist',
                'anno'        => 2014,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/john-wick.jpg',
                'carousel'    => 'assets/img/elenco.jpg',
                'video'       => 'assets/video/john-wick.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 3,
                'titolo'      => 'Die Hard - Trappola di Cristallo',
                'descrizione' => 'Un poliziotto di New York si trova in un grattacielo di Los Angeles occupato da terroristi e deve affrontarli da solo.',
                'durata'      => 132,
                'regista'     => 'John McTiernan',
                'attori'      => 'Bruce Willis, Alan Rickman',
                'anno'        => 1988,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/die-hard.jpg',
                'carousel'    => 'assets/img/elenco.jpg',
                'video'       => 'assets/video/die-hard.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 3,
                'titolo'      => 'Mission: Impossible - Fallout',
                'descrizione' => 'Ethan Hunt e il suo team devono recuperare del plutonio per evitare una catastrofe nucleare mondiale.',
                'durata'      => 147,
                'regista'     => 'Christopher McQuarrie',
                'attori'      => 'Tom Cruise, Henry Cavill',
                'anno'        => 2018,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/mission-impossible.jpg',
                'carousel'    => 'assets/img/elenco.jpg',
                'video'       => 'assets/video/mission-impossible.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 3,
                'titolo'      => 'The Dark Knight',
                'descrizione' => 'Batman affronta il Joker, un criminale caotico che vuole distruggere Gotham City e mettere alla prova i limiti morali dell\'eroe.',
                'durata'      => 152,
                'regista'     => 'Christopher Nolan',
                'attori'      => 'Christian Bale, Heath Ledger',
                'anno'        => 2008,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/the-dark-night.jpg',
                'carousel'    => 'assets/img/elenco.jpg',
                'video'       => 'assets/video/dark-night.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 3,
                'titolo'      => 'Top Gun: Maverick',
                'descrizione' => 'Maverick torna ad addestrare una nuova generazione di piloti Top Gun per una missione ad alto rischio.',
                'durata'      => 130,
                'regista'     => 'Joseph Kosinski',
                'attori'      => 'Tom Cruise, Miles Teller',
                'anno'        => 2022,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/top-gun.jpg',
                'carousel'    => 'assets/img/elenco.jpg',
                'video'       => 'assets/video/top-gun.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            // ─── CATEGORIA 4: Thriller ─────────────────────────────────────
            [
                'idCategoria' => 4,
                'titolo'      => 'Il Silenzio degli Innocenti',
                'descrizione' => 'Un agente dell\'FBI in tirocinio deve intervistare il cannibale Hannibal Lecter per rintracciare un serial killer che scuoia le sue vittime.',
                'durata'      => 118,
                'regista'     => 'Jonathan Demme',
                'attori'      => 'Jodie Foster, Anthony Hopkins',
                'anno'        => 1991,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/silenzio-innocenti.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/silenzio-innocenti.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 4,
                'titolo'      => 'Se7en',
                'descrizione' => 'Due detective indagano su una serie di omicidi ispirati ai sette vizi capitali in una città cupa e piovosa.',
                'durata'      => 127,
                'regista'     => 'David Fincher',
                'attori'      => 'Brad Pitt, Morgan Freeman',
                'anno'        => 1995,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/se7en.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/se7en.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 4,
                'titolo'      => 'Zodiac',
                'descrizione' => 'Un fumettista e due giornalisti del San Francisco Chronicle ossessionati dall\'identità del serial killer Zodiac seguono il caso per anni.',
                'durata'      => 157,
                'regista'     => 'David Fincher',
                'attori'      => 'Jake Gyllenhaal, Robert Downey Jr.',
                'anno'        => 2007,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/zodiac.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/zodiac.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 4,
                'titolo'      => 'Prisoners',
                'descrizione' => 'Quando due bambine scompaiono, un padre disperato decide di prendere la giustizia in mano mentre un detective lavora al caso.',
                'durata'      => 153,
                'regista'     => 'Denis Villeneuve',
                'attori'      => 'Hugh Jackman, Jake Gyllenhaal',
                'anno'        => 2013,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/prisoners.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/prisoners.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 4,
                'titolo'      => 'Gone Girl',
                'descrizione' => 'La sparizione di una donna nel giorno del quinto anniversario di matrimonio porta il marito sotto l\'occhio del ciclone dei media e della polizia.',
                'durata'      => 149,
                'regista'     => 'David Fincher',
                'attori'      => 'Ben Affleck, Rosamund Pike',
                'anno'        => 2014,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/gone-girl.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/gone-girl.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 4,
                'titolo'      => 'No Country for Old Men',
                'descrizione' => 'Un cacciatore del Texas trova per caso una valigia piena di denaro sporco e diventa il bersaglio di un implacabile sicario.',
                'durata'      => 122,
                'regista'     => 'Joel Coen, Ethan Coen',
                'attori'      => 'Tommy Lee Jones, Javier Bardem',
                'anno'        => 2007,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/no-country.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/no-country.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 4,
                'titolo'      => 'Parasite',
                'descrizione' => 'Una famiglia povera si infiltra abilmente nella vita di una ricca famiglia di Seul, con conseguenze inaspettate e devastanti.',
                'durata'      => 132,
                'regista'     => 'Bong Joon-ho',
                'attori'      => 'Song Kang-ho, Lee Sun-kyun',
                'anno'        => 2019,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/parasite.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/parasite.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],

            // ─── CATEGORIA 5: Drammatico ────────────────────────────────────
            [
                'idCategoria' => 5,
                'titolo'      => 'Il Padrino',
                'descrizione' => 'La saga della famiglia mafiosa dei Corleone, dalle origini del patriarca Don Vito fino al passaggio di testimone al figlio Michael.',
                'durata'      => 175,
                'regista'     => 'Francis Ford Coppola',
                'attori'      => 'Marlon Brando, Al Pacino, James Caan',
                'anno'        => 1972,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/il-padrino.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/il-padrino.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 5,
                'titolo'      => 'Schindler\'s List',
                'descrizione' => 'Durante la Seconda Guerra Mondiale, l\'imprenditore tedesco Oskar Schindler salva oltre mille ebrei polacchi dallo sterminio nazista.',
                'durata'      => 195,
                'regista'     => 'Steven Spielberg',
                'attori'      => 'Liam Neeson, Ben Kingsley',
                'anno'        => 1993,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/schindler-list.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/schindler.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 5,
                'titolo'      => 'Forrest Gump',
                'descrizione' => 'La storia di un uomo con QI basso che, suo malgrado, diventa testimone e protagonista di alcuni dei momenti più importanti della storia americana.',
                'durata'      => 142,
                'regista'     => 'Robert Zemeckis',
                'attori'      => 'Tom Hanks, Robin Wright',
                'anno'        => 1994,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/forrest-gump.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/forest.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 5,
                'titolo'      => 'The Shawshank Redemption',
                'descrizione' => 'Un banchiere condannato ingiustamente per omicidio trova conforto e redenzione nell\'amicizia con un compagno di prigione.',
                'durata'      => 142,
                'regista'     => 'Frank Darabont',
                'attori'      => 'Tim Robbins, Morgan Freeman',
                'anno'        => 1994,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/shawshank.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/shawshank.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 5,
                'titolo'      => 'Goodfellas',
                'descrizione' => 'La storia vera di Henry Hill, un gangster che dalla giovinezza alla maturità vive e racconta dall\'interno il mondo della mafia newyorkese.',
                'durata'      => 146,
                'regista'     => 'Martin Scorsese',
                'attori'      => 'Ray Liotta, Robert De Niro, Joe Pesci',
                'anno'        => 1990,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/goodfellas.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/goodfellas.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 5,
                'titolo'      => 'Into the Wild',
                'descrizione' => 'Un giovane neolaureato abbandona tutto per intraprendere un viaggio verso l\'Alaska, cercando libertà e contatto con la natura.',
                'durata'      => 148,
                'regista'     => 'Sean Penn',
                'attori'      => 'Emile Hirsch, Marcia Gay Harden',
                'anno'        => 2007,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/into-the-wild.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/the-wild.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria' => 5,
                'titolo'      => 'A Beautiful Mind',
                'descrizione' => 'La storia vera del matematico John Nash, genio della teoria dei giochi, e la sua battaglia contro la schizofrenia paranoide.',
                'durata'      => 135,
                'regista'     => 'Ron Howard',
                'attori'      => 'Russell Crowe, Jennifer Connelly',
                'anno'        => 2001,
                'visualizzato'=> 1,
                'locandina'   => 'assets/img/beautiful-mind.jpg',
                'carousel'    => 'assets/img/drammatico.jpg',
                'video'       => 'assets/video/beautiful-mind.mp4',
                'created_at'  => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
        ];

        foreach ($film as $f) {
            Film::create($f);
        }

        $this->command->info('Inseriti ' . count($film) . ' film (7 per categoria: Horror, Commedia, Azione).');
    }
}
