<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\SerieTv;
use Carbon\Carbon;

class SerieTvSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        SerieTv::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
        $now = Carbon::now();

        $serieTV = [
            // ─── CATEGORIA 1: Horror ────────────────────────────────────────
            [
                'idCategoria'    => 1,
                'nome'           => 'La Casa dei Segreti',
                'descrizione'    => 'Una famiglia si trasferisce in una villa isolata e inizia a scoprire i terribili segreti che nasconde.',
                'totaleStagioni' => 1,
                'regista'        => 'Marco Ferretti',
                'attori'         => 'Anna Conti, Luca Bianchi, Sara Greco',
                'annoInizio'     => 2023,
                'annoFine'       => null,
                'locandina'      => 'assets/img/casaSegreti.jpg',
                'carousel'       => 'assets/img/horror.jpg',
                'video'          => 'assets/video/casaSegreti.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 1,
                'nome'           => 'Notte Senza Fine',
                'descrizione'    => 'In un piccolo borgo di montagna il sole smette di sorgere. Gli abitanti affrontano un orrore antico.',
                'totaleStagioni' => 1,
                'regista'        => 'Elena Russo',
                'attori'         => 'Pietro Gallo, Marta Conti, Ivan Serra',
                'annoInizio'     => 2024,
                'annoFine'       => null,
                'locandina'      => 'assets/img/NotteFine.jpg',
                'carousel'       => 'assets/img/horror.jpg',
                'video'          => 'assets/video/notteFine.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 1,
                'nome'           => 'Il Culto',
                'descrizione'    => 'Una giornalista infiltrata in una setta scopre rituali oscuri che risalgono a secoli fa.',
                'totaleStagioni' => 1,
                'regista'        => 'Giorgio Amato',
                'attori'         => 'Carla Bruni, Franco Neri, Tina Volpe',
                'annoInizio'     => 2025,
                'annoFine'       => null,
                'locandina'      => 'assets/img/ilCulto.jpg',
                'carousel'       => 'assets/img/horror.jpg',
                'video'          => 'assets/video/ilCulto.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 1,
                'nome'           => 'Radici Nere',
                'descrizione'    => 'Un botanico studia una pianta carnivora dai poteri inspiegabili rinvenuta in una foresta dimenticata.',
                'totaleStagioni' => 1,
                'regista'        => 'Simone Ardo',
                'attori'         => 'Greta Fumi, Paolo Serri, Nadia Volta',
                'annoInizio'     => 2024,
                'annoFine'       => null,
                'locandina'      => 'assets/img/radiciNere.jpg',
                'carousel'       => 'assets/img/horror.jpg',
                'video'          => 'assets/video/radiciNere.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 1,
                'nome'           => 'Specchio Spezzato',
                'descrizione'    => 'Una psicologa inizia a dubitare della propria sanità mentale dopo una serie di eventi soprannaturali nel suo studio.',
                'totaleStagioni' => 1,
                'regista'        => 'Ilaria Conzo',
                'attori'         => 'Roberta Fiori, Enzo Lari, Claudia Masi',
                'annoInizio'     => 2025,
                'annoFine'       => null,
                'locandina'      => 'assets/img/specchioSpezzato.jpg',
                'carousel'       => 'assets/img/horror.jpg',
                'video'          => 'assets/video/specchioSpezzato.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],

            // ─── CATEGORIA 2: Commedia ──────────────────────────────────────
            [
                'idCategoria'    => 2,
                'nome'           => 'Tutto in Famiglia',
                'descrizione'    => 'Le esilaranti avventure quotidiane di una famiglia italiana disfunzionale alle prese con le sfide della vita moderna.',
                'totaleStagioni' => 2,
                'regista'        => 'Giulia Moretti',
                'attori'         => 'Paolo Ricci, Elena Fabbri, Gianni Costa',
                'annoInizio'     => 2022,
                'annoFine'       => 2023,
                'locandina'      => 'assets/img/tuttoFamiglia.jpg',
                'carousel'       => 'assets/img/commedia.jpg',
                'video'          => 'assets/video/tuttoInFamiglia.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 2,
                'nome'           => 'Ufficio Disastri',
                'descrizione'    => 'I dipendenti di un ufficio caotico sopravvivono tra scadenze impossibili e colleghi assurdi.',
                'totaleStagioni' => 1,
                'regista'        => 'Simona Greco',
                'attori'         => 'Andrea Levi, Lucia Mori, Stefano Riva',
                'annoInizio'     => 2024,
                'annoFine'       => null,
                'locandina'      => 'assets/img/ufficio.jpg',
                'carousel'       => 'assets/img/commedia.jpg',
                'video'          => 'assets/video/ufficioDisastri.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 2,
                'nome'           => 'Chef per Caso',
                'descrizione'    => 'Un ingegnere senza talenti culinari eredita un ristorante stellato. Il caos è garantito.',
                'totaleStagioni' => 1,
                'regista'        => 'Marco De Rosa',
                'attori'         => 'Filippo Bruni, Sandra Galli, Ottavio Seri',
                'annoInizio'     => 2025,
                'annoFine'       => null,
                'locandina'      => 'assets/img/chef.jpg',
                'carousel'       => 'assets/img/commedia.jpg',
                'video'          => 'assets/video/chefCaso.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 2,
                'nome'           => 'Affitti in Tilt',
                'descrizione'    => 'Quattro coinquilini incompatibili condividono un monolocale a Milano. Ogni giorno è una nuova catastrofe.',
                'totaleStagioni' => 1,
                'regista'        => 'Daria Fonti',
                'attori'         => 'Mario Cori, Tina Albi, Sergio Nucci',
                'annoInizio'     => 2023,
                'annoFine'       => null,
                'locandina'      => 'assets/img/affitti.jpg',
                'carousel'       => 'assets/img/commedia.jpg',
                'video'          => 'assets/video/affittiTilt.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 2,
                'nome'           => 'Il Sindaco Sprovveduto',
                'descrizione'    => 'Un giovane influencer viene eletto sindaco per errore e deve governare una cittadina di provincia.',
                'totaleStagioni' => 1,
                'regista'        => 'Luca Perni',
                'attori'         => 'Cristiano Valli, Miriam Soru, Fausto Deni',
                'annoInizio'     => 2024,
                'annoFine'       => null,
                'locandina'      => 'assets/img/sindaco.jpg',
                'carousel'       => 'assets/img/commedia.jpg',
                'video'          => 'assets/video/sindacoSopravvissuto.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],

            // ─── CATEGORIA 3: Azione ────────────────────────────────────────
            [
                'idCategoria'    => 3,
                'nome'           => 'Operazione Tempesta',
                'descrizione'    => 'Un agente sotto copertura viene coinvolto in una pericolosa rete di terrorismo internazionale.',
                'totaleStagioni' => 1,
                'regista'        => 'Roberto Mancini',
                'attori'         => 'Francesco Bruno, Chiara Neri, Antonio Galli',
                'annoInizio'     => 2024,
                'annoFine'       => null,
                'locandina'      => 'assets/img/operazioneTempesta.jpg',
                'carousel'       => 'assets/img/elenco.jpg',
                'video'          => 'assets/video/operazioneTempesta.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 3,
                'nome'           => 'Unità Zero',
                'descrizione'    => 'Una squadra speciale off-the-books affronta minacce che i governi non possono ammettere di conoscere.',
                'totaleStagioni' => 1,
                'regista'        => 'Dario Ferrari',
                'attori'         => 'Vittorio Cane, Rosa Fermi, Aldo Pinto',
                'annoInizio'     => 2023,
                'annoFine'       => null,
                'locandina'      => 'assets/img/zero.jpg',
                'carousel'       => 'assets/img/elenco.jpg',
                'video'          => 'assets/video/unitaZero.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 3,
                'nome'           => 'Frontiera',
                'descrizione'    => 'Agenti di confine scoprono un traffico internazionale che coinvolge figure insospettabili ai massimi livelli.',
                'totaleStagioni' => 1,
                'regista'        => 'Laura Conti',
                'attori'         => 'Marco Elia, Serena Forte, Bruno Sala',
                'annoInizio'     => 2025,
                'annoFine'       => null,
                'locandina'      => 'assets/img/frontiera.jpg',
                'carousel'       => 'assets/img/elenco.jpg',
                'video'          => 'assets/video/Frontiera.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 3,
                'nome'           => 'Cacciatori di Ombre',
                'descrizione'    => "Un ex militare guida una squadra di mercenari nell'operazione più rischiosa della loro vita.",
                'totaleStagioni' => 1,
                'regista'        => 'Andrea Rosi',
                'attori'         => 'Fabio Leni, Irene Gava, Rocco Pari',
                'annoInizio'     => 2024,
                'annoFine'       => null,
                'locandina'      => 'assets/img/cacciatoriOmbre.jpg',
                'carousel'       => 'assets/img/elenco.jpg',
                'video'          => 'assets/video/cacciatoriOmbre.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 3,
                'nome'           => 'Velocità Critica',
                'descrizione'    => 'Una pilota di rally viene reclutata dai servizi segreti per una missione che attraversa tutta Europa.',
                'totaleStagioni' => 1,
                'regista'        => 'Valeria Toci',
                'attori'         => 'Alessia Brun, Sergio Marci, Tito Gala',
                'annoInizio'     => 2025,
                'annoFine'       => null,
                'locandina'      => 'assets/img/velocità.jpg',
                'carousel'       => 'assets/img/elenco.jpg',
                'video'          => 'assets/video/velocitaCritica.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],

            // ─── CATEGORIA 4: Thriller ─────────────────────────────────────
            [
                'idCategoria'    => 4,
                'nome'           => 'Codice Oscuro',
                'descrizione'    => 'Una detective brillante indaga su una serie di omicidi collegati da un misterioso codice cifrato.',
                'totaleStagioni' => 1,
                'regista'        => 'Laura Vitale',
                'attori'         => 'Silvia Russo, Marco Colombo, Ines Ferrara',
                'annoInizio'     => 2023,
                'annoFine'       => null,
                'locandina'      => 'assets/img/codiceOscuro.jpg',
                'carousel'       => 'assets/img/elenco.jpg',
                'video'          => 'assets/video/codiceOscuro.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 4,
                'nome'           => 'Doppio Gioco',
                'descrizione'    => 'Un avvocato difensore scopre che il suo cliente è innocente, ma qualcuno di molto potente lo vuole condannato.',
                'totaleStagioni' => 1,
                'regista'        => 'Renato Scala',
                'attori'         => 'Giulia Neri, Saverio Brun, Monica Tosi',
                'annoInizio'     => 2024,
                'annoFine'       => null,
                'locandina'      => 'assets/img/doppioGioco.jpg',
                'carousel'       => 'assets/img/elenco.jpg',
                'video'          => 'assets/video/doppioGioco.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 4,
                'nome'           => 'La Testimone',
                'descrizione'    => 'Una donna assiste a un omicidio per caso. Da quel momento diventa la preda di chi non vuole testimoni.',
                'totaleStagioni' => 1,
                'regista'        => 'Paola Verdi',
                'attori'         => 'Elena Santi, Roberto Luca, Vito Fari',
                'annoInizio'     => 2025,
                'annoFine'       => null,
                'locandina'      => 'assets/img/testimone.jpg',
                'carousel'       => 'assets/img/elenco.jpg',
                'video'          => 'assets/video/testimone.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 4,
                'nome'           => 'Profilo Falso',
                'descrizione'    => "Un esperto di cybercrime viene ingannato da un'identità digitale costruita per manipolarlo dall'interno.",
                'totaleStagioni' => 1,
                'regista'        => 'Giorgio Pelu',
                'attori'         => 'Nico Arti, Caterina Luso, Dino Vela',
                'annoInizio'     => 2024,
                'annoFine'       => null,
                'locandina'      => 'assets/img/profiloBasso.jpg',
                'carousel'       => 'assets/img/elenco.jpg',
                'video'          => 'assets/video/profiloFalso.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 4,
                'nome'           => 'Il Collezionista',
                'descrizione'    => "Un profiler della polizia scientifica insegue un killer seriale che lascia oggetti d'antiquariato sulle scene del crimine.",
                'totaleStagioni' => 1,
                'regista'        => 'Sara Monti',
                'attori'         => 'Bruno Orsi, Lidia Fari, Giacomo Eno',
                'annoInizio'     => 2025,
                'annoFine'       => null,
                'locandina'      => 'assets/img/collezionista.jpg',
                'carousel'       => 'assets/img/elenco.jpg',
                'video'          => 'assets/video/collezionista.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],

            // ─── CATEGORIA 5: Drammatico ────────────────────────────────────
            [
                'idCategoria'    => 5,
                'nome'           => 'Oltre il Confine',
                'descrizione'    => 'Il viaggio umano di un gruppo di migranti che lasciano tutto per cercare una vita migliore in Europa.',
                'totaleStagioni' => 1,
                'regista'        => 'Davide Esposito',
                'attori'         => 'Amara Diallo, Pietro Marino, Sofia De Luca',
                'annoInizio'     => 2024,
                'annoFine'       => null,
                'locandina'      => 'assets/img/oltreConfine.jpg',
                'carousel'       => 'assets/img/drammatico.jpg',
                'video'          => 'assets/video/oltreConfine.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 5,
                'nome'           => 'Il Tempo Ritrovato',
                'descrizione'    => 'Tre generazioni di una famiglia si ritrovano dopo decenni. Il passato riemerge con tutta la sua forza.',
                'totaleStagioni' => 1,
                'regista'        => 'Anna Gentile',
                'attori'         => 'Carlo Masi, Francesca Levi, Gioia Rina',
                'annoInizio'     => 2023,
                'annoFine'       => null,
                'locandina'      => 'assets/img/tempoRitrovato.jpg',
                'carousel'       => 'assets/img/drammatico.jpg',
                'video'          => 'assets/video/tempoRitrovato.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 5,
                'nome'           => 'Voci Lontane',
                'descrizione'    => "Un musicista sordo riacquista l'udito dopo anni e deve reimparare a vivere con tutti i suoni del mondo.",
                'totaleStagioni' => 1,
                'regista'        => 'Matteo Sola',
                'attori'         => 'Luca Tani, Sara Blu, Daniele Fico',
                'annoInizio'     => 2025,
                'annoFine'       => null,
                'locandina'      => 'assets/img/vociLontane.jpg',
                'carousel'       => 'assets/img/drammatico.jpg',
                'video'          => 'assets/video/vociLontane.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 5,
                'nome'           => 'La Stagione dei Ritorni',
                'descrizione'    => "Un medico torna nel paesino natio dopo vent'anni e deve fare i conti con le ferite mai rimarginate del passato.",
                'totaleStagioni' => 1,
                'regista'        => 'Chiara Seri',
                'attori'         => 'Alfredo Corti, Nora Beni, Lucio Fani',
                'annoInizio'     => 2024,
                'annoFine'       => null,
                'locandina'      => 'assets/img/stagioneRitorni.jpg',
                'carousel'       => 'assets/img/drammatico.jpg',
                'video'          => 'assets/video/stagioniRitorni.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'idCategoria'    => 5,
                'nome'           => 'Sotto la Stessa Stella',
                'descrizione'    => 'Due fratelli separati da piccoli si ritrovano adulti su fronti opposti di un conflitto sociale che divide una città.',
                'totaleStagioni' => 1,
                'regista'        => 'Emilio Vani',
                'attori'         => 'Samuele Rugi, Marta Foli, Diego Arco',
                'annoInizio'     => 2025,
                'annoFine'       => null,
                'locandina'      => 'assets/img/stessaStella.jpg',
                'carousel'       => 'assets/img/drammatico.jpg',
                'video'          => 'assets/video/stessaStella.mp4',
                'created_at'     => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
        ];

        foreach ($serieTV as $serie) {
            SerieTv::create($serie);
        }

        $this->command->info('Inserite ' . count($serieTV) . ' serie TV (5 per categoria: Horror, Commedia, Azione, Thriller, Drammatico).');
    }
}
